[package]
name = "adventofcode2019"
version = "0.1.0"
authors = ["Mark Lee"]
edition = "2018"

publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
